version: "3.8"

services:
  namenode:
    image: lucasfs/hadoop-namenode
    networks:
      - cluster_net
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - target: 9870
        published: 9870
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == primary

  datanode:
    image: lucasfs/hadoop-datanode
    networks:
      - cluster_net
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == worker

volumes:
  datanode:
  namenode:

networks:
  cluster_net:
    external: true
    name: hadoop-net  